package model.entity;
// Generated 19/04/2018 11:31:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String login;
     private String senha;
     private Date cadastro;
     private Set managers = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String login, String senha, Date cadastro, Set managers) {
       this.login = login;
       this.senha = senha;
       this.cadastro = cadastro;
       this.managers = managers;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getCadastro() {
        return this.cadastro;
    }
    
    public void setCadastro(Date cadastro) {
        this.cadastro = cadastro;
    }
    public Set getManagers() {
        return this.managers;
    }
    
    public void setManagers(Set managers) {
        this.managers = managers;
    }




}


